<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>default</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\EGOIST.Application\EGOIST.Application.csproj" />
        <ProjectReference Include="..\EGOIST.Domain\EGOIST.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="MetadataExtractor" Version="2.8.1" />
        <PackageReference Include="LLamaSharp.kernel-memory" Version="0.16.0" />
        <PackageReference Include="Microsoft.KernelMemory.AI.LlamaSharp" Version="0.71.240820.1" />
        <PackageReference Include="Microsoft.KernelMemory.Core" Version="0.71.240820.1" />

        <PackageReference Include="SixLabors.ImageSharp" Version="3.1.5" />

        <PackageReference Include="YoutubeExplode" Version="6.4.0" />
        <PackageReference Include="DuckDuckGoSearch" Version="4.20.2" />
        <PackageReference Include="ReverseMarkdown" Version="4.6.0" />
    </ItemGroup>

</Project>
